name: Spell Check
on:
  pull_request:
    branches:
      - main
      - feature/notes-v2
    paths:
      -  "**/*.md"

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Spelling
        uses: codespell-project/actions-codespell@v2
        with:
          # check in mentioned dictionaries
          builtin: clear,rare,informal,code,names
          # Ignore specific words that are actually correct (comma separated)
          ignore_words_list: "shri,prakash,shukla,devops"
          # Set to true to check filenames as well
          check_filenames: true
